# The URL the site will be built for
base_url = "https://zola-site-eight.vercel.app"
# The site title and description; used in feeds by default.
title = "方寸之间"
description = "记录我的所见所闻所得"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "hermit_zola"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# Whether dotfiles at the root level of the output directory are preserved when (re)building the site.
# Enabling this also prevents the deletion of the output folder itself on rebuilds.
preserve_dotfiles_in_output = false

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
           {name = "tags", rss = true}
]

highlight_theme = "base16-ocean-dark"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Put all your custom variables here
home_subtitle = "“一切有为法，如梦幻泡影，如露亦如电，应作如是观”"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "twitter", link = "https://twitter.com/realSanmoji" },
    { name = "github", link = "https://github.com/baddate" },
    { name = "email", link = "mailto:me@sanmoji.xyz" }
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.disqus]
enable = false
# Take this from your Disqus account
shortname = "my-supa-dupa-blog"

[extra.author]
name = "Sanmoji"
email = "me@sanmoji.xyz"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
